name: Deploy

on:
  push:
    branches:
    - main
    - development
custom:
  enabled:
    dev: false
    prod: true

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: main branch based on prod stage
        if: 
        run: echo "Deploying to prod stage on branch main"
      - name: dev branch based on dev stage
        if: 
        run: echo "Deploying to dev stage server on branch development"
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          npx ncc build index.ts
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=myfunctionCI --zip-file=fileb://deploy.zip
