name: Deploy

on:
  push:
    branches:
    - main
    - development
    
 

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          

  dev-check:
    if: main; then
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch main"
         else
      - run: echo "Deploying to development server on branch development"       
 

      - name: npm install
        env:
          CI: true
        run: |
          npm ci



 
