name: Deploy

on:
  push:
    branches:
    - main
    - development

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: conditional command based on stage
          if main; then
          steps:
            - run: echo "Deploying to production server on branch main"
          else
          steps:
            - run: echo "Deploying to development server on branch development"
            
          fi

      - name: npm install
        env:
          CI: true
        run: |
          npm ci



 
