name: Deploy

on:
  push:
    branches:
    - main
    - development
    - release
   
 

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Serverless Framework
        run: npm install -g serverless 
      - name: Install dependencies
        run: npm install 
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: enviroment production
        run: sls deploy -s prod
      - if:  ${{ github.ref == 'refs/heads/development' }}
        name: enviroment development
        run: sls deploy -s dev
      - if:  ${{ github.ref == 'refs/heads/release' }}
        name: enviroment release
        run:  sls deploy -s hml
        





 
