name: Deploy

on:
  push:
    branches:
    - main
    - development
   
 

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: IF
        run: echo "Deploying to production server on branch main"
      - if:  ${{ github.ref == 'refs/heads/development' }}
        name: Else
        run:  echo "Deploying to development server on branch development"


      - name: npm install
        env:
          CI: true
        run: |
          npm ci



 
